In [1]:
import tensorflow as tf

In [2]:
from tensorflow.keras import layers
import numpy as np

데이터 불러오기

In [3]:
cifar10 = tf.keras.datasets.cifar10
(x_train,y_train),(x_test,y_test) = cifar10.load_data()

데이터 살펴보기  
RGB로 이루어져 있으며 훈련이터는 총 5만개임

In [4]:
x_train.shape

(50000, 32, 32, 3)

In [5]:
image_R = x_train[:,:,:,0]
image_G = x_train[:,:,:,1]
image_B = x_train[:,:,:,2]

In [6]:
print(image_R.shape)
print(image_G.shape)
print(image_B.shape)

(50000, 32, 32)
(50000, 32, 32)
(50000, 32, 32)


In [7]:
image_R[0]

array([[ 59,  43,  50, ..., 158, 152, 148],
       [ 16,   0,  18, ..., 123, 119, 122],
       [ 25,  16,  49, ..., 118, 120, 109],
       ...,
       [208, 201, 198, ..., 160,  56,  53],
       [180, 173, 186, ..., 184,  97,  83],
       [177, 168, 179, ..., 216, 151, 123]], dtype=uint8)

In [8]:
image_G[0]

array([[ 62,  46,  48, ..., 132, 125, 124],
       [ 20,   0,   8, ...,  88,  83,  87],
       [ 24,   7,  27, ...,  84,  84,  73],
       ...,
       [170, 153, 161, ..., 133,  31,  34],
       [139, 123, 144, ..., 148,  62,  53],
       [144, 129, 142, ..., 184, 118,  92]], dtype=uint8)

In [9]:
image_B[0]

array([[ 63,  45,  43, ..., 108, 102, 103],
       [ 20,   0,   0, ...,  55,  50,  57],
       [ 21,   0,   8, ...,  50,  50,  42],
       ...,
       [ 96,  34,  26, ...,  70,   7,  20],
       [ 96,  42,  30, ...,  94,  34,  34],
       [116,  94,  87, ..., 140,  84,  72]], dtype=uint8)

데이터 전처리

In [10]:
#데이터 정규화
train_image_R = x_train / 255.0

In [11]:
train_image_R.shape

(50000, 32, 32, 3)

In [12]:
y_train[0]

array([6], dtype=uint8)

개구리로 추정됨(?)

In [13]:
import matplotlib.pyplot as plt
plt.figure()
plt.imshow(x_train[0])
plt.colorbar()
plt.grid(False)
plt.show()

<Figure size 640x480 with 2 Axes>

tenforflow의 라이브러리를 활용하여 구현 vs tensorflow만을 이용하여 구현?

tf.keras를 이용하여 (5)층을 쌓으면서 모델 만들기

In [14]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(32,32,3)),
    tf.keras.layers.Dense(60, activation='relu'),
    tf.keras.layers.Dense(60, activation='relu'),
    tf.keras.layers.Dense(60, activation='relu'),
    tf.keras.layers.Dense(60, activation='relu'),
    tf.keras.layers.Dense(60, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

In [15]:
model.compile(optimizer='adam', #Use Adam Optimizer
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [16]:
model.fit(train_image_R, y_train, epochs=20,batch_size = 100)

Train on 50000 samples
Epoch 1/20
50000/50000 [==============================] - 2s 42us/sample - loss: 1.9182 - accuracy: 0.2998
Epoch 2/20
50000/50000 [==============================] - 1s 30us/sample - loss: 1.7399 - accuracy: 0.3724
Epoch 3/20
50000/50000 [==============================] - 1s 30us/sample - loss: 1.6752 - accuracy: 0.3993
Epoch 4/20
50000/50000 [==============================] - 1s 29us/sample - loss: 1.6204 - accuracy: 0.4173
Epoch 5/20
50000/50000 [==============================] - 1s 29us/sample - loss: 1.5763 - accuracy: 0.4322
Epoch 6/20
50000/50000 [==============================] - 2s 30us/sample - loss: 1.5484 - accuracy: 0.4433
Epoch 7/20
50000/50000 [==============================] - 1s 30us/sample - loss: 1.5286 - accuracy: 0.4516
Epoch 8/20
50000/50000 [==============================] - 2s 30us/sample - loss: 1.5095 - accuracy: 0.4573
Epoch 9/20
50000/50000 [==============================] - 1s 30us/sample - loss: 1.4950 - accuracy: 0.4626
Epoch 10/20
50

In [17]:
test_images = x_test / np.max(x_test[0])

In [18]:
test_loss, test_acc = model.evaluate(test_images,  y_test, verbose=2)

print('\n테스트 정확도:', round(test_acc*100,3),"%")

10000/1 - 1s - loss: 1.4208 - accuracy: 0.4701

테스트 정확도: 47.01 %


In [ ]:
#tf.keras.utils.plot_model(model)

tf.keras를 이용하지 않고 모델 만들기